- args:
    relationship: users
    table:
      name: user_sessions
      schema: public
  type: drop_relationship
- args:
    relationship: sessions
    table:
      name: users
      schema: public
  type: drop_relationship