- args:
    cascade: true
    sql: |-
      CREATE TABLE roles (
        name text NOT NULL PRIMARY KEY
      );

      INSERT INTO roles (name) VALUES ('admin');
      INSERT INTO roles (name) VALUES ('user');

      CREATE TABLE users (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        email text NOT NULL UNIQUE,
        password text NOT NULL,
        is_active boolean NOT NULL DEFAULT false,
        secret_token uuid NOT NULL,
        default_role text NOT NULL DEFAULT 'user',
        created_at timestamp with time zone NOT NULL DEFAULT now(),
        FOREIGN KEY (default_role) REFERENCES roles (name)
      );

      CREATE TABLE user_roles (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        user_id uuid NOT NULL,
        role text NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT now(),
        FOREIGN KEY (user_id) REFERENCES users (id),
        FOREIGN KEY (role) REFERENCES roles (name),
        UNIQUE (user_id, role)
      );

      CREATE TABLE refresh_tokens (
        id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        refresh_token uuid NOT NULL UNIQUE,
        user_id uuid NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT now(),
        FOREIGN KEY (user_id) REFERENCES users (id)
      );
  type: run_sql
- args:
    name: roles
    schema: public
  type: add_existing_table_or_view
- args:
    name: users
    schema: public
  type: add_existing_table_or_view
- args:
    name: user_roles
    schema: public
  type: add_existing_table_or_view
- args:
    name: refresh_tokens
    schema: public
  type: add_existing_table_or_view
